[PARSER]
    Name        json
    Format      json
    Time_Key    timestamp
    Time_Format %s%3N

[PARSER]
    Name        waf_json
    Format      json
    Time_Key    timestamp
    Time_Format %Y-%m-%dT%H:%M:%SZ
