#!/usr/bin/env python3
"""
auto_pr.py — 분석 결과 → GitHub PR 자동 생성

analyzer가 HIGH 위험으로 판정한 IP를 terraform/waf_blocked_ips.auto.tfvars에 반영하고
GitHub PR을 자동으로 생성한다. 운영자는 PR을 검토한 뒤 승인하면 Terraform Apply가 실행된다.

사용 예:
    python scripts/auto_pr.py                       # output/ 최신 JSON 자동 탐지
    python scripts/auto_pr.py --analysis output/analysis_20260622_120000.json
    python scripts/auto_pr.py --dry-run             # PR 생성 없이 내용만 출력

환경 변수:
    GITHUB_TOKEN  GitHub Personal Access Token (scope: repo)
"""
import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

ROOT = Path(__file__).parent.parent
OUTPUT_DIR = ROOT / "output"
TFVARS_PATH = ROOT / "terraform" / "waf_blocked_ips.auto.tfvars"
BASE_BRANCH = "main"
API = "https://api.github.com"


def _load_repo() -> str:
    try:
        import yaml
        cfg = yaml.safe_load((ROOT / "platform.yaml").read_text(encoding="utf-8"))
        return cfg["integrations"]["github_repo"]
    except Exception:
        return "goormSecurity/cloud-security-platform"


REPO = _load_repo()


# ── GitHub API 헬퍼 ─────────────────────────────────────────────

def _gh(method: str, path: str, token: str, body: dict = None):
    url = f"{API}{path}"
    data = json.dumps(body).encode() if body else None
    req = Request(
        url,
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "Content-Type": "application/json",
        },
    )
    try:
        with urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except HTTPError as e:
        body_text = e.read().decode()
        raise RuntimeError(f"GitHub API {method} {path} → {e.code}: {body_text}") from e


# ── 분석 결과 로딩 ───────────────────────────────────────────────

def _load_latest_analysis(analysis_path: str = None) -> dict:
    if analysis_path:
        p = Path(analysis_path)
    else:
        candidates = sorted(OUTPUT_DIR.glob("analysis_*.json"))
        if not candidates:
            sys.exit(f"[auto_pr] output/ 폴더에 analysis_*.json 파일이 없습니다.")
        p = candidates[-1]
    print(f"[auto_pr] 분석 파일 로드: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _extract_high_risk_ips(analysis: dict) -> list[str]:
    ips = []
    for entry in analysis.get("top_ips", []):
        if entry.get("risk_level") == "HIGH":
            ip = entry.get("ip", "")
            if ip and "/" not in ip:
                ips.append(f"{ip}/32")
            elif ip:
                ips.append(ip)
    return sorted(set(ips))


# ── Terraform tfvars 생성 ─────────────────────────────────────────

def _generate_tfvars(ips: list[str]) -> str:
    if not ips:
        return 'blocked_ips = []\n'
    quoted = ",\n  ".join(f'"{ip}"' for ip in ips)
    return f"# auto-generated by auto_pr.py — {datetime.now().isoformat()}\n# 수동 수정 금지: 다음 실행 시 덮어씁니다\nblocked_ips = [\n  {quoted},\n]\n"


# ── GitHub PR 생성 ────────────────────────────────────────────────

def _get_base_sha(token: str) -> str:
    resp = _gh("GET", f"/repos/{REPO}/git/ref/heads/{BASE_BRANCH}", token)
    return resp["object"]["sha"]


def _create_branch(token: str, branch: str, base_sha: str):
    _gh("POST", f"/repos/{REPO}/git/refs", token, {
        "ref": f"refs/heads/{branch}",
        "sha": base_sha,
    })
    print(f"[auto_pr] 브랜치 생성: {branch}")


def _push_file(token: str, branch: str, content: str, message: str):
    import base64

    path = "terraform/waf_blocked_ips.auto.tfvars"
    # 기존 파일 SHA 조회 (업데이트 시 필요)
    sha = None
    try:
        existing = _gh("GET", f"/repos/{REPO}/contents/{path}?ref={branch}", token)
        sha = existing.get("sha")
    except RuntimeError:
        pass  # 신규 파일

    body = {
        "message": message,
        "content": base64.b64encode(content.encode()).decode(),
        "branch": branch,
    }
    if sha:
        body["sha"] = sha

    _gh("PUT", f"/repos/{REPO}/contents/{path}", token, body)
    print(f"[auto_pr] 파일 커밋: {path}")


def _create_pr(token: str, branch: str, title: str, body: str) -> dict:
    resp = _gh("POST", f"/repos/{REPO}/pulls", token, {
        "title": title,
        "body": body,
        "head": branch,
        "base": BASE_BRANCH,
    })
    return resp


def _build_pr_body(analysis: dict, ips: list[str]) -> str:
    summary = analysis.get("summary", {})
    generated_at = analysis.get("generated_at", "")
    total_req = summary.get("total_requests", 0)
    block_rate = summary.get("block_rate", 0)
    high_risk = summary.get("high_risk_ips", 0)

    ip_table = "\n".join(f"| `{ip}` | HIGH |" for ip in ips) if ips else "| (없음) | - |"

    return f"""## 개요

분석 엔진이 **HIGH 위험** 으로 판정한 IP {len(ips)}개를 WAF 차단 목록에 추가합니다.

> 분석 시각: `{generated_at}`

## 분석 요약

| 항목 | 값 |
|---|---|
| 총 요청 수 | {total_req:,} |
| 현재 차단율 | {block_rate:.1%} |
| HIGH 위험 IP 수 | {high_risk} |

## 추가 차단 IP 목록

| IP (CIDR) | 위험도 |
|---|---|
{ip_table}

## 변경 파일

- `terraform/waf_blocked_ips.auto.tfvars` — WAF IP 차단 목록 자동 갱신

## 검토 체크리스트

- [ ] HIGH 위험 판정 근거 확인 (output/ 폴더의 분석 JSON 참조)
- [ ] Infracost 비용 영향 확인 (이 PR에 자동 댓글 게시됨)
- [ ] 오탐 여부 검토
- [ ] 승인 후 Terraform Apply → AWS WAF 자동 반영

---
*🤖 auto_pr.py에 의해 자동 생성됨*
"""


def run(analysis_path: str = None, dry_run: bool = False):
    token = os.environ.get("GITHUB_TOKEN")
    if not token and not dry_run:
        sys.exit("[auto_pr] GITHUB_TOKEN 환경 변수가 필요합니다.")

    analysis = _load_latest_analysis(analysis_path)
    ips = _extract_high_risk_ips(analysis)
    tfvars_content = _generate_tfvars(ips)

    print(f"[auto_pr] HIGH 위험 IP: {len(ips)}개")
    for ip in ips:
        print(f"  → {ip}")

    # 로컬 파일도 함께 갱신
    TFVARS_PATH.write_text(tfvars_content, encoding="utf-8")
    print(f"[auto_pr] 로컬 파일 저장: {TFVARS_PATH.relative_to(ROOT)}")

    if not ips:
        print("[auto_pr] HIGH 위험 IP 없음 - PR 생성 생략 (차단 목록 변경 없음)")
        return

    if dry_run:
        print("\n[auto_pr] --dry-run: PR 생성 생략")
        print("── PR 내용 미리보기 ─────────────────────────────────")
        print(_build_pr_body(analysis, ips))
        return

    ts = datetime.now().strftime("%Y%m%d%H%M%S")
    branch = f"auto/waf-blocklist-{ts}"
    title = f"fix(waf): HIGH 위험 IP {len(ips)}개 차단 목록 추가"
    commit_msg = f"chore(waf): blocked_ips 자동 갱신 ({len(ips)}개, {ts})"
    pr_body = _build_pr_body(analysis, ips)

    base_sha = _get_base_sha(token)
    _create_branch(token, branch, base_sha)
    _push_file(token, branch, tfvars_content, commit_msg)
    pr = _create_pr(token, branch, title, pr_body)

    print(f"\n[auto_pr] PR 생성 완료!")
    print(f"  URL : {pr.get('html_url')}")
    print(f"  번호: #{pr.get('number')}")


def main():
    p = argparse.ArgumentParser(description="분석 결과 → GitHub PR 자동 생성")
    p.add_argument("--analysis", default=None, help="analysis JSON 경로 (생략 시 최신 파일 자동 선택)")
    p.add_argument("--dry-run", action="store_true", help="PR 생성 없이 내용만 출력")
    args = p.parse_args()
    run(analysis_path=args.analysis, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
